# Generated by Django 2.2.7 on 2019-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='toiletPaper',
            field=models.FloatField(),
        ),
    ]
