# Generated by Django 2.2.7 on 2019-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191129_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='refillDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='usageDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
