# Generated by Django 3.0 on 2019-12-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('toiletPaper', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usageDateTime', models.DateTimeField()),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Toilet')),
            ],
        ),
        migrations.CreateModel(
            name='Refiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refillDateTime', models.DateTimeField()),
                ('refiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Refiller')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Toilet')),
            ],
        ),
    ]
