# Generated by Django 2.2.7 on 2019-11-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('toiletPaper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usageDateTime', models.DateTimeField()),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Toilet')),
            ],
        ),
        migrations.CreateModel(
            name='Revill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revillDateTime', models.DateTimeField()),
                ('reviller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Reviller')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Toilet')),
            ],
        ),
    ]
