# Generated by Django 3.0 on 2019-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191129_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='name',
        ),
    ]
